export enum MessageStatus {
  UNCONFIRMED_L1_TO_L2_MESSAGE = 0,
  FAILED_L1_TO_L2_MESSAGE = 1,
  STATE_ROOT_NOT_PUBLISHED = 2,
  READY_TO_PROVE = 3,
  IN_CHALLENGE_PERIOD = 4,
  READY_FOR_RELAY = 5,
  RELAYED = 6,
}
