export const SUPERCHAIN_MAINNETS = [
  "optimism",
  "base",
  "zora",
  "pgn",
  "mode",
  "orderly",
  "lyra",
  "lumio-mainnet",
  "metal-mainnet",
  "fraxtal-mainnet-l2",
  "lisk-mainnet",
  "cyber-mainnet",
  "redstone-mainnet",
  "mint-mainnet-0",
  // "kroma",
  "xterio-chain-eth",
  "swan-chain",
];

export const SUPERCHAIN_TESTNETS = [
  "op-sepolia",
  "base-sepolia",
  "zora-sepolia-0thyhxtf5e",
  "pgn-sepolia-i4td3ji6i0",
  "mode-sepolia-vtnhnpim72",
  "orderly-l2-4460-sepolia-8tc3sd7dvy",
  "metal-l2-testnet-3bbzi9kufn",
  "fraxtal-testnet-l2",
  "lisk-sepolia",
  "cyber-testnet",
  "lattice-testnet",
  "mint-sepolia-testnet-ijtsrc4ffq",
  "xterio-eth-testnet",
  "celo-testnet",
];
