/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface AcrossAvailableRouteDto {
  originChainId: number;
  originToken: string;
  originTokenSymbol: string;
  destinationChainId: number;
  destinationToken: string;
  destinationTokenSymbol: string;
}
