/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type AcrossTransactionType = typeof AcrossTransactionType[keyof typeof AcrossTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AcrossTransactionType = {
  'across-bridge': 'across-bridge',
} as const;
