/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ChainDto } from './chainDto';
import type { AcrossContractAddressesDto } from './acrossContractAddressesDto';

export interface AcrossDomainDto {
  id: string;
  chain: ChainDto;
  contractAddresses: AcrossContractAddressesDto;
  createdAt: string;
  updatedAt: string;
}
