/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { AcrossBridgeMetadataDataDto } from './acrossBridgeMetadataDataDto';

export interface AcrossBridgeMetadataDto {
  data: AcrossBridgeMetadataDataDto;
  from: string;
  to: string;
  type: string;
}
