/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface AcrossBridgeMetadataDataDto {
  inputAmount: string;
  inputTokenAddress: string;
  isEth: boolean;
  outputAmount: string;
  outputTokenAddress: string;
}
