/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ActivityDtoTransactionsItem } from './activityDtoTransactionsItem';

export interface ActivityDto {
  transactions: ActivityDtoTransactionsItem[];
}
