/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { BridgeWithdrawalDto } from './bridgeWithdrawalDto';
import type { PortalDepositDto } from './portalDepositDto';
import type { ForcedWithdrawalDto } from './forcedWithdrawalDto';
import type { ArbitrumDepositRetryableDto } from './arbitrumDepositRetryableDto';
import type { ArbitrumDepositEthDto } from './arbitrumDepositEthDto';
import type { ArbitrumWithdrawalDto } from './arbitrumWithdrawalDto';
import type { ArbitrumForcedWithdrawalDto } from './arbitrumForcedWithdrawalDto';
import type { CctpBridgeDto } from './cctpBridgeDto';
import type { AcrossBridgeDto } from './acrossBridgeDto';
import type { HyperlaneBridgeDto } from './hyperlaneBridgeDto';

export type ActivityV3DtoTransactionsItem = BridgeWithdrawalDto | PortalDepositDto | ForcedWithdrawalDto | ArbitrumDepositRetryableDto | ArbitrumDepositEthDto | ArbitrumWithdrawalDto | ArbitrumForcedWithdrawalDto | CctpBridgeDto | AcrossBridgeDto | HyperlaneBridgeDto;
