/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ActivityV3DtoTransactionsItem } from './activityV3DtoTransactionsItem';

export interface ActivityV3Dto {
  actionRequiredCount: number;
  /** @nullable */
  hasWithdrawalReadyToFinalize: string | null;
  inProgressCount: number;
  total: number;
  transactions: ActivityV3DtoTransactionsItem[];
}
