/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DeploymentStatus } from './deploymentStatus';

export interface ActiveDeploymentStatus {
  status: DeploymentStatus;
}
