/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface AddressDto {
  address: string;
  chainName: string;
  gasAddress: string;
  granted: boolean;
  id: string;
  name: string;
  paid: boolean;
  paymentAddress: string;
}
