/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type AmountTooLargeRouteErrorDtoType = typeof AmountTooLargeRouteErrorDtoType[keyof typeof AmountTooLargeRouteErrorDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AmountTooLargeRouteErrorDtoType = {
  GenericError: 'GenericError',
  AmountTooSmall: 'AmountTooSmall',
  AmountTooLarge: 'AmountTooLarge',
  Paused: 'Paused',
  Disabled: 'Disabled',
} as const;
