/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type AmountTooSmallRouteErrorDtoType = typeof AmountTooSmallRouteErrorDtoType[keyof typeof AmountTooSmallRouteErrorDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AmountTooSmallRouteErrorDtoType = {
  GenericError: 'GenericError',
  AmountTooSmall: 'AmountTooSmall',
  AmountTooLarge: 'AmountTooLarge',
  Paused: 'Paused',
  Disabled: 'Disabled',
} as const;
