/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type ArbitrumTransactionType = typeof ArbitrumTransactionType[keyof typeof ArbitrumTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArbitrumTransactionType = {
  'arbitrum-deposit-eth': 'arbitrum-deposit-eth',
  'arbitrum-deposit-retryable': 'arbitrum-deposit-retryable',
  'arbitrum-withdrawal': 'arbitrum-withdrawal',
  'arbitrum-forced-withdrawal': 'arbitrum-forced-withdrawal',
} as const;
