/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ArbitrumTransactionType } from './arbitrumTransactionType';
import type { ArbitrumWithdrawalDtoMetadata } from './arbitrumWithdrawalDtoMetadata';
import type { DeploymentDto } from './deploymentDto';
import type { ConfirmationDto } from './confirmationDto';

export interface ArbitrumWithdrawalDto {
  type: ArbitrumTransactionType;
  id: string;
  metadata: ArbitrumWithdrawalDtoMetadata;
  deployment: DeploymentDto;
  deploymentId: string;
  withdrawal: ConfirmationDto;
  finalise?: ConfirmationDto;
  status: number;
  createdAt: string;
  updatedAt: string;
}
