/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DeploymentDto } from './deploymentDto';
import type { ConfirmationDto } from './confirmationDto';
import type { ArbitrumDepositEthDtoMetadata } from './arbitrumDepositEthDtoMetadata';
import type { ArbitrumTransactionType } from './arbitrumTransactionType';

export interface ArbitrumDepositEthDto {
  createdAt: string;
  deployment: DeploymentDto;
  deposit: ConfirmationDto;
  id: string;
  l2TransactionHash: string;
  metadata: ArbitrumDepositEthDtoMetadata;
  relay?: ConfirmationDto;
  type: ArbitrumTransactionType;
  updatedAt: string;
}
