/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { L2ArbitrumContractAddressesDto } from './l2ArbitrumContractAddressesDto';

export interface ArbitrumContractAddressesDto {
  inbox: string;
  outbox: string;
  rollup: string;
  l2GatewayRouter: string;
  l1GatewayRouter: string;
  bridge: string;
  l2: L2ArbitrumContractAddressesDto;
}
