/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ArbitrumTransactionType } from './arbitrumTransactionType';
import type { ArbitrumForcedWithdrawalDtoDeposit } from './arbitrumForcedWithdrawalDtoDeposit';
import type { ArbitrumWithdrawalDto } from './arbitrumWithdrawalDto';

export interface ArbitrumForcedWithdrawalDto {
  type: ArbitrumTransactionType;
  id: string;
  deposit: ArbitrumForcedWithdrawalDtoDeposit;
  withdrawal?: ArbitrumWithdrawalDto;
}
