/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { EthDepositDto } from './ethDepositDto';
import type { TokenDepositDto } from './tokenDepositDto';
import type { NftDepositDto } from './nftDepositDto';
import type { AcrossBridgeMetadataDto } from './acrossBridgeMetadataDto';

export type ArbitrumDepositRetryableDtoMetadata = EthDepositDto | TokenDepositDto | NftDepositDto | AcrossBridgeMetadataDto;
