/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { AssetDenomUnitDto } from './assetDenomUnitDto';
import type { AssetDtoIbc } from './assetDtoIbc';
import type { AssetDtoLogoURIs } from './assetDtoLogoURIs';

export interface AssetDto {
  address?: string;
  base: string;
  coingecko_id?: string;
  denom_units: AssetDenomUnitDto[];
  description?: string;
  display: string;
  ibc: AssetDtoIbc;
  keywords?: string[];
  logo_URIs: AssetDtoLogoURIs;
  name: string;
  symbol: string;
  type_asset?: string;
}
