/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface AuthRegisterLoginDto {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
}
