/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type BannerItemDtoType = typeof BannerItemDtoType[keyof typeof BannerItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BannerItemDtoType = {
  banner: 'banner',
} as const;
