/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ChosenNftDto } from './chosenNftDto';
import type { BannerItemDtoType } from './bannerItemDtoType';

export interface BannerItemDto {
  nft?: ChosenNftDto;
  type: BannerItemDtoType;
  value: string;
}
