/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { BlacklistDtoData } from './blacklistDtoData';

export interface BlacklistDto {
  data: BlacklistDtoData;
}
