/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { EthDepositDto } from './ethDepositDto';
import type { TokenDepositDto } from './tokenDepositDto';
import type { AcrossBridgeMetadataDto } from './acrossBridgeMetadataDto';
import type { LzBridgeMetadataDto } from './lzBridgeMetadataDto';

export type BridgeWithdrawalDtoMetadata = EthDepositDto | TokenDepositDto | AcrossBridgeMetadataDto | LzBridgeMetadataDto;
