/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { EthDepositDto } from './ethDepositDto';
import type { TokenDepositDto } from './tokenDepositDto';
import type { NftDepositDto } from './nftDepositDto';

export type BridgeWithdrawalDtoMetadata = EthDepositDto | TokenDepositDto | NftDepositDto;
