/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface BridgeNftChainConfigDto {
  address: string;
  bridgeAddress: string;
  chainId: string;
  isNative: boolean;
}
