/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { HyperlaneRouterDto } from './hyperlaneRouterDto';

export type BridgeControllerGetRoutesParams = {
fromTokenAddress: string;
fromChainId: string;
toTokenAddress: string;
toChainId: string;
sender: string;
recipient: string;
amount: string;
graffiti: string;
forceViaL1: boolean;
hyperlaneFromTokenRouterAddress?: string;
hyperlaneToTokenRouterAddress?: string;
opBridgedUsdcAdapter?: string;
lzAdapter?: string;
from: HyperlaneRouterDto;
to: HyperlaneRouterDto;
};
