/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { OptimismTransactionType } from './optimismTransactionType';
import type { BridgeWithdrawalDtoMetadata } from './bridgeWithdrawalDtoMetadata';
import type { DeploymentDto } from './deploymentDto';
import type { ConfirmationDto } from './confirmationDto';
import type { ProveConfirmationDto } from './proveConfirmationDto';

export interface BridgeWithdrawalDto {
  type: OptimismTransactionType;
  id: string;
  l1ChainId: number;
  l2ChainId: number;
  status: number;
  metadata: BridgeWithdrawalDtoMetadata;
  deployment: DeploymentDto;
  deploymentId: string;
  withdrawal: ConfirmationDto;
  prove?: ProveConfirmationDto;
  finalise?: ConfirmationDto;
  createdAt: string;
  updatedAt: string;
}
