/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type BridgeControllerGetRoutesParams = {
fromTokenAddress: string;
fromChainId: string;
toTokenAddress: string;
toChainId: string;
sender: string;
recipient: string;
amount: string;
graffiti: string;
};
