/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ConfirmationDto } from './confirmationDto';
import type { BridgeWithdrawalDtoMetadata } from './bridgeWithdrawalDtoMetadata';
import type { ProveConfirmationDto } from './proveConfirmationDto';
import type { OptimismTransactionType } from './optimismTransactionType';

export interface BridgeWithdrawalDto {
  createdAt: string;
  deploymentId: string;
  finalise?: ConfirmationDto;
  id: string;
  l1ChainId: number;
  l2ChainId: number;
  metadata: BridgeWithdrawalDtoMetadata;
  prove?: ProveConfirmationDto;
  status: number;
  type: OptimismTransactionType;
  updatedAt: string;
  withdrawal: ConfirmationDto;
}
