/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ConfirmationDto } from './confirmationDto';
import type { DeploymentDto } from './deploymentDto';
import type { ChainDto } from './chainDto';
import type { CctpTransactionType } from './cctpTransactionType';

export interface CctpBridgeDto {
  amount: string;
  bridge: ConfirmationDto;
  createdAt: string;
  deployment: DeploymentDto;
  deploymentId: string;
  from: ChainDto;
  id: string;
  relay?: ConfirmationDto;
  to: ChainDto;
  token: string;
  type: CctpTransactionType;
  updatedAt: string;
}
