/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface CctpContractAddressesDto {
  tokenMessenger: string;
  messageTransmitter: string;
  bridge: string;
  minter: string;
}
