/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { CctpContractAddressesDto } from './cctpContractAddressesDto';

export interface CctpDomainDto {
  chainId: number;
  contractAddresses: CctpContractAddressesDto;
  createdAt: string;
  domain: number;
  id: string;
}
