/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type CctpTransactionType = typeof CctpTransactionType[keyof typeof CctpTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CctpTransactionType = {
  'cctp-bridge': 'cctp-bridge',
} as const;
