/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { CctpTransactionType } from './cctpTransactionType';
import type { DeploymentDto } from './deploymentDto';
import type { ConfirmationDto } from './confirmationDto';
import type { ChainDto } from './chainDto';

export interface CctpBridgeDto {
  type: CctpTransactionType;
  id: string;
  amount: string;
  token: string;
  deployment: DeploymentDto;
  deploymentId: string;
  bridge: ConfirmationDto;
  relay?: ConfirmationDto;
  from: ChainDto;
  to: ChainDto;
  createdAt: string;
  updatedAt: string;
}
