/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface ChainNativeCurrencyDto {
  decimals: number;
  name: string;
  symbol: string;
}
