/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface CreateMainnetConduitDeploymentDto {
  conduitId: string;
  displayName: string;
  key: string;
  slug: string;
}
