/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoPhoto } from './createUserDtoPhoto';
import type { CreateUserDtoRole } from './createUserDtoRole';
import type { Status } from './status';

export interface CreateUserDto {
  email: string | null;
  firstName: string | null;
  hash?: string | null;
  lastName: string | null;
  password?: string;
  photo?: CreateUserDtoPhoto;
  provider?: string;
  role?: CreateUserDtoRole;
  socialId?: string | null;
  status?: Status;
}
