/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { OptimismContractAddressesDto } from './optimismContractAddressesDto';
import type { ArbitrumContractAddressesDto } from './arbitrumContractAddressesDto';

export type DeploymentDtoContractAddresses = OptimismContractAddressesDto | ArbitrumContractAddressesDto;
