/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DeploymentThemeDto } from './deploymentThemeDto';

/**
 * @nullable
 */
export type DeploymentDtoTheme = DeploymentThemeDto | null;
