/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { OptimismConfigDto } from './optimismConfigDto';
import type { ArbitrumConfigDto } from './arbitrumConfigDto';

export type DeploymentDtoConfig = OptimismConfigDto | ArbitrumConfigDto;
