/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DeploymentThemeDto } from './deploymentThemeDto';

export type DeploymentDtoTheme = DeploymentThemeDto | null;
