/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ChainDto } from './chainDto';
import type { DeploymentDtoContractAddresses } from './deploymentDtoContractAddresses';
import type { DeploymentDtoConfig } from './deploymentDtoConfig';
import type { DeploymentDtoType } from './deploymentDtoType';
import type { DeploymentDtoFamily } from './deploymentDtoFamily';
import type { DeploymentDtoTheme } from './deploymentDtoTheme';
import type { FetchedMultichainTokenDto } from './fetchedMultichainTokenDto';
import type { DeploymentDtoArbitrumNativeToken } from './deploymentDtoArbitrumNativeToken';
import type { DeploymentDtoTos } from './deploymentDtoTos';
import type { DeploymentDtoStatus } from './deploymentDtoStatus';

export interface DeploymentDto {
  id: string;
  createdAt: string;
  name: string;
  displayName: string;
  l1: ChainDto;
  l2: ChainDto;
  contractAddresses: DeploymentDtoContractAddresses;
  config: DeploymentDtoConfig;
  conduitId: string | null;
  type: DeploymentDtoType;
  family: DeploymentDtoFamily;
  supportsNftBridging: boolean;
  theme: DeploymentDtoTheme;
  tokens: FetchedMultichainTokenDto[];
  arbitrumNativeToken: DeploymentDtoArbitrumNativeToken;
  tos: DeploymentDtoTos;
  status: DeploymentDtoStatus;
}
