/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ToSDto } from './toSDto';

/**
 * @nullable
 */
export type DeploymentDtoTos = ToSDto | null;
