/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ThemeDto } from './themeDto';
import type { LinkDto } from './linkDto';

export interface DeploymentThemeDto {
  theme: ThemeDto;
  links: LinkDto[];
  id: string;
  createdAt: string;
  updatedAt: string;
}
