/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type DeploymentStatus = typeof DeploymentStatus[keyof typeof DeploymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeploymentStatus = {
  active: 'active',
  trial: 'trial',
} as const;
