/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DeploymentDtoContractAddresses } from './deploymentDtoContractAddresses';
import type { DeploymentFamily } from './deploymentFamily';
import type { ChainDto } from './chainDto';
import type { DeploymentType } from './deploymentType';

export interface DeploymentDto {
  conduitId: string | null;
  contractAddresses: DeploymentDtoContractAddresses;
  createdAt: string;
  displayName: string;
  family: DeploymentFamily;
  id: string;
  l1: ChainDto;
  l2: ChainDto;
  name: string;
  supportsNftBridging: boolean;
  type: DeploymentType;
}
