/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type DeploymentDtoFamily = typeof DeploymentDtoFamily[keyof typeof DeploymentDtoFamily];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeploymentDtoFamily = {
  optimism: 'optimism',
  arbitrum: 'arbitrum',
} as const;
