/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DraftDtoJson } from './draftDtoJson';

export interface DraftDto {
  chainName: string;
  createdAt: string;
  discussionLink?: string;
  error?: string;
  id: string;
  json: DraftDtoJson;
  proposalId?: number;
  transactionHash?: string;
  type: string;
  updatedAt: string;
}
