/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { EstimateDto } from './estimateDto';

export interface EstimateGasResponseDto {
  estimates: EstimateDto[];
  success: boolean;
}
