/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { TransactionDto } from './transactionDto';

export interface EstimateGasDto {
  from: string;
  transactions: TransactionDto[];
}
