/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { EthDepositDataDto } from './ethDepositDataDto';

export interface EthDepositDto {
  type: string;
  from: string;
  to: string;
  data: EthDepositDataDto;
}
