/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface FetchedTokenDto {
  name: string;
  symbol: string;
  decimals: number;
  chainId: number;
  address: string;
  logoURI: string;
  bridge: string;
}
