/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface FetchedOptimismTokenDto {
  address: string;
  bridge: string;
  chainId: number;
  decimals: number;
  logoURI: string;
  name: string;
  symbol: string;
}
