/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { RouteErrorType } from './routeErrorType';

export interface GenericRouteErrorDto {
  error: string;
  type: RouteErrorType;
}
