/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { GetHyperlaneActivityDto } from './getHyperlaneActivityDto';

export interface GetActivityV3Dto {
  address: string;
  /** @nullable */
  cursor: string | null;
  deploymentIds: string[];
  hyperlane?: GetHyperlaneActivityDto;
  includeAcross: boolean;
}
