/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { GovernanceDraft } from './governanceDraft';
import type { GovernanceUserDtoClass } from './governanceUserDtoClass';

export interface GovernanceUser {
  address: string;
  chainName: string;
  createdAt: string;
  drafts: GovernanceDraft[];
  dtoClass?: GovernanceUserDtoClass;
  id: string;
  publicKey: string;
  updatedAt: string;
}
