/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { WeightedVoteOptionDto } from './weightedVoteOptionDto';

export interface GovernanceVote {
  blockNumber?: number;
  chainId: string;
  chainName: string;
  id: string;
  metadata?: string;
  option?: number;
  options?: WeightedVoteOptionDto[];
  proposalId: number;
  voter: string;
}
