/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { GovernanceUser } from './governanceUser';
import type { GovernanceDraftDtoClass } from './governanceDraftDtoClass';
import type { GovernanceDraftJson } from './governanceDraftJson';

export interface GovernanceDraft {
  chainName: string;
  createdAt: string;
  createdBy: GovernanceUser;
  discussionLink?: string;
  dtoClass?: GovernanceDraftDtoClass;
  error?: string;
  id: string;
  json: GovernanceDraftJson;
  proposalId?: number;
  transactionHash?: string;
  type: string;
  updatedAt: string;
}
