/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type HyperlaneRouterDtoType = typeof HyperlaneRouterDtoType[keyof typeof HyperlaneRouterDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HyperlaneRouterDtoType = {
  ERC20: 'ERC20',
  ERC721: 'ERC721',
  EvmNative: 'EvmNative',
  EvmHypNative: 'EvmHypNative',
  EvmHypCollateral: 'EvmHypCollateral',
  EvmHypCollateralFiat: 'EvmHypCollateralFiat',
  EvmHypSynthetic: 'EvmHypSynthetic',
  EvmHypXERC20: 'EvmHypXERC20',
  EvmHypXERC20Lockbox: 'EvmHypXERC20Lockbox',
  SealevelSpl: 'SealevelSpl',
  SealevelSpl2022: 'SealevelSpl2022',
  SealevelNative: 'SealevelNative',
  SealevelHypNative: 'SealevelHypNative',
  SealevelHypCollateral: 'SealevelHypCollateral',
  SealevelHypSynthetic: 'SealevelHypSynthetic',
  CosmosIcs20: 'CosmosIcs20',
  CosmosIcs721: 'CosmosIcs721',
  CosmosNative: 'CosmosNative',
  CosmosIbc: 'CosmosIbc',
  CW20: 'CW20',
  CWNative: 'CWNative',
  CW721: 'CW721',
  CwHypNative: 'CwHypNative',
  CwHypCollateral: 'CwHypCollateral',
  CwHypSynthetic: 'CwHypSynthetic',
} as const;
