/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type HyperlaneTransactionType = typeof HyperlaneTransactionType[keyof typeof HyperlaneTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HyperlaneTransactionType = {
  'hyperlane-bridge': 'hyperlane-bridge',
} as const;
