/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { HyperlaneRouterDto } from './hyperlaneRouterDto';

export interface HyperlaneRouteRequestDto {
  from: HyperlaneRouterDto;
  to: HyperlaneRouterDto;
}
