/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ConfirmationDto } from './confirmationDto';
import type { HyperlaneTransactionType } from './hyperlaneTransactionType';

export interface HyperlaneBridgeDto {
  amount: string;
  createdAt: string;
  duration: number;
  from: string;
  fromDomain: number;
  hyperlaneMessageId: string;
  id: string;
  receive?: ConfirmationDto;
  send: ConfirmationDto;
  to: string;
  toDomain: number;
  token: string;
  type: HyperlaneTransactionType;
  updatedAt: string;
}
