/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface InitiatingTransactionDto {
  chainId: string;
  data: string;
  to: string;
  value: string;
}
