/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type ItemTypes = typeof ItemTypes[keyof typeof ItemTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemTypes = {
  text: 'text',
  links: 'links',
  pfp: 'pfp',
  banner: 'banner',
  'nft-gallery': 'nft-gallery',
  'music-nft': 'music-nft',
  'youtube-video': 'youtube-video',
} as const;
