/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { LinksItemDtoLinks } from './linksItemDtoLinks';
import type { LinksItemDtoType } from './linksItemDtoType';

export interface LinksItemDto {
  links: LinksItemDtoLinks;
  type: LinksItemDtoType;
}
