/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { TextItemDto } from './textItemDto';
import type { LinksItemDto } from './linksItemDto';
import type { PfpItemDto } from './pfpItemDto';
import type { BannerItemDto } from './bannerItemDto';
import type { NftGalleryItemDto } from './nftGalleryItemDto';
import type { MusicNftItemDto } from './musicNftItemDto';
import type { YoutubeVideoItemDto } from './youtubeVideoItemDto';

export type LinkDtoData = TextItemDto | LinksItemDto | PfpItemDto | BannerItemDto | NftGalleryItemDto | MusicNftItemDto | YoutubeVideoItemDto;
