/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type LinksItemDtoType = typeof LinksItemDtoType[keyof typeof LinksItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinksItemDtoType = {
  links: 'links',
} as const;
