/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { LzBridgeMetadataDataDto } from './lzBridgeMetadataDataDto';

export interface LzBridgeMetadataDto {
  data: LzBridgeMetadataDataDto;
  from: string;
  type: string;
}
