/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { LzContractAddressesDto } from './lzContractAddressesDto';

export interface LzDomainDto {
  chainId: number;
  contractAddresses: LzContractAddressesDto;
  createdAt: string;
  eId: number;
  id: string;
}
