/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { NftDepositDataDto } from './nftDepositDataDto';

export interface NftDepositDto {
  data: NftDepositDataDto;
  from: string;
  to: string;
  type: string;
}
