/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type NftGalleryItemDtoType = typeof NftGalleryItemDtoType[keyof typeof NftGalleryItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NftGalleryItemDtoType = {
  'nft-gallery': 'nft-gallery',
} as const;
