/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { L2OptimismContractAddressesDto } from './l2OptimismContractAddressesDto';

export interface OptimismContractAddressesDto {
  addressManager: string;
  bondManager: string;
  canonicalTransactionChain: string;
  disputeGameFactory?: string;
  l1CrossDomainMessenger: string;
  l1StandardBridge: string;
  l2: L2OptimismContractAddressesDto;
  l2OutputOracle: string;
  optimismPortal: string;
  stateCommitmentChain: string;
  systemConfig?: string;
}
