/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type OptimismTransactionType = typeof OptimismTransactionType[keyof typeof OptimismTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OptimismTransactionType = {
  withdrawal: 'withdrawal',
  deposit: 'deposit',
  'forced-withdrawal': 'forced-withdrawal',
} as const;
