/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { L2OptimismContractAddressesDto } from './l2OptimismContractAddressesDto';

export interface OptimismContractAddressesDto {
  disputeGameFactory?: string;
  l1CrossDomainMessenger: string;
  l1StandardBridge: string;
  l2: L2OptimismContractAddressesDto;
  l2OutputOracle?: string;
  optimismPortal: string;
  systemConfig?: string;
}
