/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface OptimismConfigDto {
  finalizationPeriodSeconds: number;
  submissionIntervalSeconds: number;
  blockTimeSeconds: number;
  disputeGameFinalityDelaySeconds?: number;
  dataAvailabilityChallengePeriodSeconds?: number;
}
