/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface OptimismConfigDto {
  blockTimeSeconds: number;
  finalizationPeriodSeconds: number;
  submissionIntervalSeconds: number;
}
