/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ParamsDtoAuthParams } from './paramsDtoAuthParams';
import type { BankParams } from './bankParams';
import type { ParamsDtoDepositParams } from './paramsDtoDepositParams';
import type { ParamsDtoDistributionParams } from './paramsDtoDistributionParams';
import type { StakingPoolDto } from './stakingPoolDto';
import type { ParamsDtoSlashingParams } from './paramsDtoSlashingParams';
import type { ParamsDtoStakingParams } from './paramsDtoStakingParams';
import type { CoinDto } from './coinDto';
import type { ParamsDtoTallyParams } from './paramsDtoTallyParams';
import type { ParamsDtoVotingParams } from './paramsDtoVotingParams';

export interface ParamsDto {
  authParams: ParamsDtoAuthParams;
  bankParams: BankParams;
  depositParams: ParamsDtoDepositParams;
  distributionParams: ParamsDtoDistributionParams;
  pool: StakingPoolDto;
  slashingParams: ParamsDtoSlashingParams;
  stakingParams: ParamsDtoStakingParams;
  supply: CoinDto;
  tallyParams: ParamsDtoTallyParams;
  votingParams: ParamsDtoVotingParams;
}
