/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DurationDto } from './durationDto';

export type ParamsDtoStakingParams = {
  bondDenom?: string;
  historicalEntries?: number;
  maxEntries?: number;
  maxValidators?: number;
  minCommissionRate?: string;
  unbondingTime?: DurationDto;
};
