/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { PausedRouteErrorDtoType } from './pausedRouteErrorDtoType';

export interface PausedRouteErrorDto {
  type: PausedRouteErrorDtoType;
}
