/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type PfpItemDtoType = typeof PfpItemDtoType[keyof typeof PfpItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PfpItemDtoType = {
  pfp: 'pfp',
} as const;
