/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type ProposalDtoStatus = typeof ProposalDtoStatus[keyof typeof ProposalDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalDtoStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_MINUS_1: -1,
} as const;
