/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { AnyDto } from './anyDto';
import type { TallyResultDto } from './tallyResultDto';
import type { ProposalDtoStatus } from './proposalDtoStatus';
import type { CoinDto } from './coinDto';

export interface ProposalDto {
  content?: AnyDto;
  depositEndTime?: string;
  discussionLink?: string;
  finalTallyResult?: TallyResultDto;
  id: string;
  messages?: AnyDto[];
  metadata?: string;
  proposalId: number;
  proposer?: string;
  status: ProposalDtoStatus;
  submitTime?: string;
  totalDeposit?: CoinDto[];
  votingEndTime?: string;
  votingStartTime?: string;
}
