/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { ProposalDto } from './proposalDto';

export interface ProposalsResponseDto {
  nextPage?: number;
  proposals: ProposalDto[];
  total: number;
}
