/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface RegisterAddressDto {
  chainName: string;
  payload: string;
  publicKey: string;
  signature: string;
}
