/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { RouteRequestDto } from './routeRequestDto';
import type { RouteResultDto } from './routeResultDto';

export interface RouteResponseDto {
  request: RouteRequestDto;
  results: RouteResultDto[];
}
