/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { RouteProvider } from './routeProvider';
import type { RouteResponseDtoResult } from './routeResponseDtoResult';

export interface RouteResponseDto {
  id: RouteProvider;
  result: RouteResponseDtoResult;
}
