/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { RouteStepTransactionDto } from './routeStepTransactionDto';
import type { RouteStepWaitDto } from './routeStepWaitDto';
import type { RouteStepReceiveDto } from './routeStepReceiveDto';

export type RouteQuoteDtoStepsItem = RouteStepTransactionDto | RouteStepWaitDto | RouteStepReceiveDto;
