/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type RouteProvider = typeof RouteProvider[keyof typeof RouteProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RouteProvider = {
  OptimismDeposit: 'OptimismDeposit',
  OptimismWithdrawal: 'OptimismWithdrawal',
  OptimismForcedWithdrawal: 'OptimismForcedWithdrawal',
  ArbitrumDeposit: 'ArbitrumDeposit',
  ArbitrumWithdrawal: 'ArbitrumWithdrawal',
  Cctp: 'Cctp',
  Across: 'Across',
  Hyperlane: 'Hyperlane',
} as const;
