/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type RouteStepType = typeof RouteStepType[keyof typeof RouteStepType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RouteStepType = {
  Initiate: 'Initiate',
  Prove: 'Prove',
  Finalize: 'Finalize',
  ForcedWithdrawal: 'ForcedWithdrawal',
  Wait: 'Wait',
  Receive: 'Receive',
} as const;
