/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { RouteFeeItemDto } from './routeFeeItemDto';
import type { InitiatingTransactionDto } from './initiatingTransactionDto';
import type { RouteStepItemDto } from './routeStepItemDto';

export interface RouteResponseDto {
  fees: RouteFeeItemDto[];
  gasTokenApprovalAddress?: string;
  id: string;
  initiatingTransaction: InitiatingTransactionDto;
  receive: string;
  steps: RouteStepItemDto[];
  tokenApprovalAddress?: string;
}
