/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { RouteQuoteDto } from './routeQuoteDto';
import type { GenericRouteErrorDto } from './genericRouteErrorDto';
import type { AmountTooSmallRouteErrorDto } from './amountTooSmallRouteErrorDto';
import type { AmountTooLargeRouteErrorDto } from './amountTooLargeRouteErrorDto';
import type { PausedRouteErrorDto } from './pausedRouteErrorDto';
import type { DisabledRouteErrorDto } from './disabledRouteErrorDto';

export type RouteResultDtoResult = RouteQuoteDto | GenericRouteErrorDto | AmountTooSmallRouteErrorDto | AmountTooLargeRouteErrorDto | PausedRouteErrorDto | DisabledRouteErrorDto;
