/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DurationDto } from './durationDto';

export interface SlashingParams {
  downtimeJailDuration: DurationDto;
  minSignedPerWindow: number;
  signedBlocksWindow: string;
  slashFractionDoubleSign: number;
  slashFractionDowntime: number;
}
