/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { TokenBannerDto } from './tokenBannerDto';

/**
 * @nullable
 */
export type SuperbridgeConfigDtoBanner = TokenBannerDto | null;
