/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { SuperbridgeConfigDtoBanner } from './superbridgeConfigDtoBanner';
import type { HighlightedTokens } from './highlightedTokens';

export interface SuperbridgeConfigDto {
  /** @nullable */
  banner: SuperbridgeConfigDtoBanner;
  highlightedTokens: HighlightedTokens[];
}
