/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { DeploymentFamily } from './deploymentFamily';
import type { DeploymentType } from './deploymentType';

export interface TempDto {
  family: DeploymentFamily;
  type: DeploymentType;
}
