/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { TextItemDtoType } from './textItemDtoType';

export interface TextItemDto {
  type: TextItemDtoType;
  value: string;
}
