/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface ThemeDto {
  accent?: string;
  'accent-foreground'?: string;
  background?: string;
  border?: string;
  card?: string;
  'card-foreground'?: string;
  destructive?: string;
  'destructive-foreground'?: string;
  fill?: string;
  foreground?: string;
  iconSrc?: string;
  input?: string;
  logoHeight?: number;
  logoSrc?: string;
  logoSrcDark?: string;
  logoWidth?: number;
  muted?: string;
  'muted-foreground'?: string;
  navIconSrc?: string;
  popover?: string;
  'popover-foreground'?: string;
  primary?: string;
  'primary-foreground'?: string;
  radius?: string;
  ring?: string;
  screenBgImg?: string;
  secondary?: string;
  'secondary-foreground'?: string;
}
