/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface ThemeDto {
  accent?: string;
  'accent-dark'?: string;
  'accent-foreground'?: string;
  'accent-foreground-dark'?: string;
  background?: string;
  'background-dark'?: string;
  border?: string;
  'border-dark'?: string;
  card?: string;
  'card-dark'?: string;
  'card-foreground'?: string;
  'card-foreground-dark'?: string;
  darkModeEnabled?: boolean;
  destructive?: string;
  'destructive-dark'?: string;
  'destructive-foreground'?: string;
  'destructive-foreground-dark'?: string;
  fill?: string;
  'fill-dark'?: string;
  foreground?: string;
  'foreground-dark'?: string;
  imageBackground?: string;
  imageBackgroundDark?: string;
  imageLogo?: string;
  imageLogoDark?: string;
  imageNetwork?: string;
  imageNetworkDark?: string;
  muted?: string;
  'muted-dark'?: string;
  'muted-foreground'?: string;
  'muted-foreground-dark'?: string;
  popover?: string;
  'popover-dark'?: string;
  'popover-foreground'?: string;
  'popover-foreground-dark'?: string;
  primary?: string;
  'primary-dark'?: string;
  'primary-foreground'?: string;
  'primary-foreground-dark'?: string;
  radius?: string;
}
