/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface ThemeDto {
  accent?: string;
  'accent-dark'?: string;
  'accent-foreground'?: string;
  'accent-foreground-dark'?: string;
  background?: string;
  'background-dark'?: string;
  backgroundImageBlendMode?: string;
  backgroundImageBlendModeDark?: string;
  backgroundImageOpacity?: string;
  backgroundImageOpacityDark?: string;
  backgroundImagePosition?: string;
  backgroundImageRepeat?: string;
  backgroundImageSize?: string;
  backgroundImageStyle?: string;
  border?: string;
  'border-dark'?: string;
  card?: string;
  'card-dark'?: string;
  'card-foreground'?: string;
  'card-foreground-dark'?: string;
  darkModeEnabled?: boolean;
  destructive?: string;
  'destructive-dark'?: string;
  'destructive-foreground'?: string;
  'destructive-foreground-dark'?: string;
  foreground?: string;
  'foreground-dark'?: string;
  imageBackground?: string;
  imageBackgroundDark?: string;
  imageLogo?: string;
  imageLogoDark?: string;
  imageNetwork?: string;
  imageNetworkDark?: string;
  imageOg?: string;
  imageSuperbridgeLogo?: string;
  imageSuperbridgeLogoDark?: string;
  input?: string;
  'input-dark'?: string;
  muted?: string;
  'muted-dark'?: string;
  'muted-foreground'?: string;
  'muted-foreground-dark'?: string;
  popover?: string;
  'popover-dark'?: string;
  'popover-foreground'?: string;
  'popover-foreground-dark'?: string;
  primary?: string;
  'primary-dark'?: string;
  'primary-foreground'?: string;
  'primary-foreground-dark'?: string;
  radius?: string;
  ring?: string;
  'ring-dark'?: string;
  secondary?: string;
  'secondary-dark'?: string;
  'secondary-foreground'?: string;
  'secondary-foreground-dark'?: string;
}
