/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface TokenDepositDataDto {
  amount: string;
  l1TokenAddress: string;
  l2TokenAddress: string;
}
