/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { TokenDepositDataDto } from './tokenDepositDataDto';

export interface TokenDepositDto {
  data: TokenDepositDataDto;
  from: string;
  to: string;
  type: string;
}
