/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export interface ToSDto {
  customPrivacyPolicy: string;
  customTermsOfService: string;
  forceReadPrivacyPolicy: boolean;
  forceReadTermsOfService: boolean;
}
