/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { AssetDto } from './assetDto';

export interface TracedCoinDto {
  amount: string;
  asset: AssetDto;
  chainName: string;
  denom: string;
}
