/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type TransactionStatus = typeof TransactionStatus[keyof typeof TransactionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionStatus = {
  confirmed: 'confirmed',
  reverted: 'reverted',
  dropped: 'dropped',
} as const;
