/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { UpdateUserDtoPhoto } from './updateUserDtoPhoto';
import type { UpdateUserDtoRole } from './updateUserDtoRole';
import type { Status } from './status';

export interface UpdateUserDto {
  email?: string | null;
  firstName?: string | null;
  hash?: string | null;
  lastName?: string | null;
  password?: string;
  photo?: UpdateUserDtoPhoto;
  provider?: string;
  role?: UpdateUserDtoRole;
  socialId?: string | null;
  status?: Status;
}
