/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { UserPhoto } from './userPhoto';
import type { UserRole } from './userRole';
import type { Status } from './status';

export interface User {
  createdAt: string;
  deletedAt: string;
  email: string | null;
  firstName: string | null;
  hash: string | null;
  id: number;
  lastName: string | null;
  password: string;
  photo?: UserPhoto;
  previousPassword: string;
  provider: string;
  role?: UserRole;
  socialId: string | null;
  status?: Status;
  updatedAt: string;
}
