/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type VotebotControllerGetDaosParams = {
stargaze?: unknown;
osmosis?: unknown;
juno?: unknown;
cosmoshub?: unknown;
};
