/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */
import type { VoteDtoOption } from './voteDtoOption';

export interface VoteDto {
  option: VoteDtoOption;
  proposalId: string;
  voter: string;
}
