/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * API
 * API docs
 * OpenAPI spec version: 1.0
 */

export type YoutubeVideoItemDtoType = typeof YoutubeVideoItemDtoType[keyof typeof YoutubeVideoItemDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const YoutubeVideoItemDtoType = {
  'youtube-video': 'youtube-video',
} as const;
