import {
  ancient8,
  arbitrum,
  arbitrumNova,
  arbitrumSepolia,
  avalanche,
  avalancheFuji,
  base,
  baseSepolia,
  berachainTestnet,
  berachainTestnetbArtio,
  blast,
  bob,
  bobSepolia,
  bsc,
  bscTestnet,
  celo,
  celoAlfajores,
  cyber,
  degen,
  fraxtal,
  fuse,
  gnosis,
  gravity,
  holesky,
  inEVM,
  kroma,
  linea,
  lisk,
  lukso,
  mainnet,
  manta,
  mantle,
  merlin,
  metis,
  mode,
  modeTestnet,
  moonbeam,
  optimism,
  optimismSepolia,
  pgn,
  polygon,
  polygonAmoy,
  polygonZkEvm,
  real,
  redstone,
  rollux,
  scroll,
  sei,
  sepolia,
  snax,
  snaxTestnet,
  syscoin,
  taiko,
  xLayer,
  xai,
  zetachain,
  zora,
  zoraSepolia,
} from "viem/chains";

export const chainIcons: { [chainId: number]: string | undefined } = {
  [mainnet.id]: "/img/networks/ethereum.svg",
  [sepolia.id]: "/img/networks/sepolia.svg",
  [holesky.id]: "/img/networks/sepolia.svg",
  [arbitrumSepolia.id]: "/img/networks/arbitrum-one.svg",
  [arbitrum.id]: "/img/networks/arbitrum-one.svg",
  [arbitrumNova.id]: "/img/networks/arbitrum-nova.svg",
  [syscoin.id]: "/img/networks/syscoin.svg",
  [rollux.id]: "/img/networks/rollux.svg",
  [788988]: "/img/orb3-mainnet/network.svg",
  [pgn.id]: "/img/networks/pgn.svg",
  [kroma.id]: "/img/networks/kroma.svg",
  1024: "/img/parallel/network.svg",
  [mode.id]: "/img/networks/mode.svg",
  [modeTestnet.id]: "/img/networks/mode.svg",
  [zora.id]: "/img/networks/zora.svg",
  [zoraSepolia.id]: "/img/networks/zora.svg",
  [base.id]: "/img/networks/base.svg",
  [baseSepolia.id]: "/img/networks/base.svg",
  [optimism.id]: "/img/networks/optimism.svg",
  [optimismSepolia.id]: "/img/networks/optimism.svg",
  [bsc.id]: "/img/networks/bsc.svg",
  [bscTestnet.id]: "/img/networks/bsc.svg",
  [linea.id]: "/img/networks/linea.svg",
  [fraxtal.id]: "/img/networks/frax.svg",
  [manta.id]: "/img/networks/manta.svg",
  [inEVM.id]: "/img/networks/injective.svg",
  [blast.id]: "/img/networks/blast.svg",
  [88]: "/img/networks/viction.svg",
  [ancient8.id]: "/img/networks/ancient8.svg",
  [avalanche.id]: "/img/networks/avalanche.svg",
  [scroll.id]: "/img/networks/scroll.svg",
  [polygon.id]: "/img/networks/polygon.svg",
  [48900]: "/img/networks/zircuit.svg",
  [gravity.id]: "/img/networks/gravity.png",
  [360]: "/img/networks/molten.svg",
  [480]: "/img/networks/worldchain.svg",
  [berachainTestnet.id]: "/img/networks/bera.svg",
  [berachainTestnetbArtio.id]: "/img/networks/bera.svg",
  [sei.id]: "/img/networks/sei.svg",
  [celoAlfajores.id]: "/img/networks/celo.svg",
  [celo.id]: "/img/networks/celo.svg",
  [bobSepolia.id]: "/img/networks/bob.svg",
  [bob.id]: "/img/networks/bob.svg",
  [avalancheFuji.id]: "/img/networks/avalanche.svg",
  [polygonAmoy.id]: "/img/networks/polygon.svg",
  [cyber.id]: "/img/networks/cyber.svg",
  [degen.id]: "/img/networks/degen.svg",
  [fuse.id]: "/img/networks/fuse.svg",
  [gnosis.id]: "/img/networks/gnosis.svg",
  [lisk.id]: "/img/networks/lisk.svg",
  [lukso.id]: "/img/networks/lukso.svg",
  [mantle.id]: "/img/networks/mantle.svg",
  [merlin.id]: "/img/networks/merlin.svg",
  [metis.id]: "/img/networks/metis.svg",
  [moonbeam.id]: "/img/networks/moonbeam.svg",
  [polygonZkEvm.id]: "/img/networks/polygon.svg",
  [real.id]: "/img/networks/real.svg",
  [redstone.id]: "/img/networks/redstone.svg",
  [taiko.id]: "/img/networks/taiko.svg",
  [xai.id]: "/img/networks/xia.svg",
  [zetachain.id]: "/img/networks/zeta.svg",
  [xLayer.id]: "/img/networks/xlayer.svg",
  [383353]: "/img/networks/cheesechain.svg",
  [185]: "/img/networks/mint.svg",
  [1687]: "/img/networks/mint.svg",
  [70700]: "/img/networks/proofofplay.svg",
  [648]: "/img/networks/endurance.svg",
  [132902]: "/img/networks/form.svg",
  [325000]: "/img/networks/camp.svg",
  [5115]: "/img/networks/citrea.svg",
  [33626250]: "/img/networks/suave.svg",
  [1946]: "/img/networks/sonieum.svg",
  [1996]: "/img/networks/sanko.svg",
  [984122]: "/img/networks/forma.svg",
  [1301]: "/img/networks/unichain.svg",
  [snax.id]: "/img/networks/snaxchain.svg",
  [snaxTestnet.id]: "/img/networks/snaxchain.svg",
};
